# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c00ea99b2bc2d3545a3cc0c9023edb3e4c78ef7252f627335e317135b4fef3e60a40253b0bf2d520899a5108013384aa819879a9105455b6d83326cb10a4551

test:
  secret_key_base: 3786a8b3460c117928cba0e1c59941ad1f144a599847a4a70803583a79941cfb294916e6f4b01c359a53c12bff1b3ec15685571c0608e4c44d95a58b70a09d95

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
